name: test-schedule-demo

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
jobs:
  test_schedule:                      
    runs-on: ubuntu-latest 
    permissions: 
      contents: write            
    steps:
      - name: 23f1001065@ds.study.iitm.ac.in
        run: echo "helllllllllllllllllllllllllllllllllo"
