name: test-schedule-demo

on:
  schedule:
    - cron: "36 2 * * *"
  workflow_dispatch:
jobs:
  test_schedule:                      
    runs-on: ubuntu-latest 
    permissions: 
      contents: write            
    steps:
      - name: 23f1001065@ds.study.iitm.ac.in
        run: echo "Runnig scheduled event."
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: runing create_json
        run: python3 create_json.py
      - name: commit new file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.json
          git commit -m "Update IMDb Top 250 data [skip ci]" || exit 0
          git push
            
